### PR TITLE
make m3, m3_nut and motor_dia configurable

### PR DESCRIPTION
**Pull request by domonoky2**
Next attempt :-) 

This makes the m3, m3_nut and motor_dia configurable. 
Also i added some comments.

### CODE REVIEW

**Comment by whosawhatsis** [comment]
I really prefer the \* 7/12 format for brevity rather than dividing by two then multiplying by 7/6. Also, in the stylebook in my head that only I can read, it says that all mathematical operators between two values must be preceded and followed by a space (no "m3_dia/2"), with the exception that frequently-used set ratios like 7/6 and 7/12 are considered a single value, and should be written without internal spaces. Also, I've standardized on using "size" to indicate a diameter, so things like m3_dia should instead be called m3_size. Motor_dia should be motor_shaft_size.

Sorry for being so picky. At least all of this should be fixable with find/replace.

**Comment by domonoky2** [comment]
oki, i changed all dias to sizes and used the 7/12 ratio instead of 7/6. 
I hope i didnt forgot anything.

And thank you for explaning your "stylebook" :-)

**Comment by whosawhatsis** [comment]
I've manually pulled everything up to "correct math style (spaces around operators)" into a new branch so that I can play with it. I couldn't figure out the "right" way to do it, so I fell back to the old command-C/command-V.

**Comment by whosawhatsis** [comment]
Pretty sure I found all of the bugs. It's now in master.

**Comment by whosawhatsis** [comment]
BTW, that's not what I had in mind when I mentioned using arrays. What I WAS thinking of would make the code a bit harder to read and write... I wish openscad had associative arrays...

**Comment by domonoky2** [comment]
Thanks for commiting the first part.

**Pull request closed without merging**
